import { DECLARATION } from './enums'
import path from 'path'

const SIZE_PASSWORD = 8
const START_NUMERO_CLIENT = 10000000
const DEFAULT_INDIVIDUAL_FOLDERS = [ DECLARATION.RENOUVELLEMENT, DECLARATION.PERTE]
const SESSION_COOKIE_NAME = 'id_protect'

export { 
    SIZE_PASSWORD, 
    START_NUMERO_CLIENT, 
    DEFAULT_INDIVIDUAL_FOLDERS, 
    SESSION_COOKIE_NAME
}