const enum ALERTE_TYPE {
  USER = "USER",
  DOSSIER = "DOSSIER",
  DOCUMENT = "DOCUMENT",
  ESPACE = "ESPACE",
  RENOUVELLEMENT = "RENOUVELLEMENT",
  PERTE = "PERTE",
  TOKENVERIFICATION = "TOKENVERIFICATION",
  SESSION = "SESSION",
  COFFRE = "COFFRE"
}

const enum USER_SIZESPACE {
  INDIVIDUAL = 50,
  PARTNER = 120
}

const enum DECLARATION {
    PERTE = "PERTE",
    VOL = "VOL",
    RENOUVELLEMENT = "RENOUVELLEMENT",
    PREMIRE_DEMANDE = "PREMIERE DEMANDE"
  }

  const enum USER_TYPE {
    ADMIN = "admin",
    INDIVIDUAL = "individual",
    PARTNER = "partner",
    CLIENT = "client"
  }

  const enum EMAIL_ACTION {
    VERIFY = "v",
    PASSWORD = "p"
  }
  
  const enum ADMIN_ROLE {
    SUPER = "SUPER",
    USER = "USER",
    READER = "READER"
  }

  const enum STATUS {
    EN_COURS = "EC",
    TERMINE = "VAL",
    ANNULE = "ANN",
    INFO = "INFO"
  }

  const enum ACTION {
    RENOUVELLEMENT = "RENOUVELLEMENT PIECE IDENTTITE",
    DECLARATION_PERTE = "DECLARATION DE PERTE",
    CREATION_DOSSIER = "CREATION DE DOSSIER",
    CREATION_DOSSIER_SYSTEME = "CREATION DE DOSSIER SYSTEME",
    SUPPRESSION_DOSSIER = "SUPPRESSION DE DOSSIER",
    MODIFICATION_DOSSIER = "MODIFICATION DE DOSSIER",
    CREATION_AUTORISATION = "CREATION AUTORISATION",
    VALIDATION_AUTORISATION = "VALIDATION AUTORISATION",
    SUPPRESSION_AUTORISATION = "SUPPRESSION AUTORISATION",
    DEMANDE_AUTORISATION = "DEMANDE AUTORISATION",
    CREATION_COMPTE = "CREATION DE COMPTE",
    MODIFICATION_COMPTE = "MODIFICATION DE COMPTE",
    SUPPRESSION_COMPTE = "SUPPRESSION DE COMPTE",
    RECHERCHE_ID = "RECHERCHE DOCUMENT",
    SYSTEME = "SYSTEME",
    PORTAIL = "PORTAIL",
    ADMIN = "ADMIN",
    ERREUR_MOT_DE_PASSE = "ERREUR MOT DE PASSE",
    COMPTE_SUSPENDU = "COMPTE SUSPENDU"
  }

  const enum PASSPORT_STRATEGY {
    PS_ADMIN = "localAdmin",
    PS_CLIENT = "localClient"
  }
  
  const enum ARIAD_CHOICE {
    SANDBOX = "SANDBOX",
    TEST = "TEST",
    PRODUCTION = "PRODUCTION"
  }

  export { DECLARATION, USER_TYPE, ADMIN_ROLE, ACTION, PASSPORT_STRATEGY, EMAIL_ACTION, STATUS, ALERTE_TYPE, USER_SIZESPACE, ARIAD_CHOICE }