import Vue from "vue";

export default Vue.mixin({
  data() {
    return {
      streetTypes: [
        { value: null, text: "Choisissez..." },
        { value: "RUE", text: "RUE" },
        { value: "AVENUE", text: "AVENUE" },
        { value: "BOULEVARD", text: "BOULEVARD" },
        { value: "ALLEE", text: "ALLÉE" },
        { value: "PLACE", text: "PLACE" },
        { value: "ROUTE", text: "ROUTE" },
        { value: "COURS", text: "COURS" },
        { value: "CHEMIN", text: "CHEMIN" },
        { value: "PROMENADE", text: "PROMENADE" },
        { value: "SENTE", text: "SENTE" },
        { value: "LE_BOURG", text: "LE BOURG" },
        { value: "CENTRE", text: "CENTRE" },
        { value: "CTRE_CIAL", text: "CTRE CIAL" },
        { value: "IMMEUBLE", text: "IMMEUBLE" },
        { value: "IMPASSE", text: "IMPASSE" },
        { value: "LIEU_DIT", text: "LIEU-DIT" },
        { value: "LOTISSEMENT", text: "LOTISSEMENT" },
        { value: "PASSAGE", text: "PASSAGE" },
        { value: "RESIDENCE", text: "RÉSIDENCE" },
        { value: "ROND_POINT", text: "ROND-POINT" },
        { value: "SQUARE", text: "SQUARE" },
        { value: "VILLAGE", text: "VILLAGE" },
        { value: "ZA", text: "ZA" },
        { value: "ZAC", text: "ZAC" },
        { value: "ZAD", text: "ZAD" },
        { value: "VILLA", text: "VILLA" },
        { value: "CHAUSSEE", text: "CHAUSSEE" },
        { value: "QUAI", text: "QUAI" },
        { value: "FAUBOURG", text: "FAUBOURG" },
        { value: "HAMEAU", text: "HAMEAU" },
      ],
      streetExtensions: [
        { value: null, text: "Choisissez..." },
        { value: "BIS", text: "BIS" },
        { value: "TER", text: "TER" },
        { value: "QUATER", text: "QUATER" },
        { value: "QUINQUIES", text: "QUINQUIES" },
        { value: "A", text: "A" },
        { value: "B", text: "B" },
        { value: "C", text: "C" },
      ],
      nationalityOptions: [
        {
          value: "NE_EN_FR_ET_PARENT_NE_EN_FR",
          text:
            "Vous êtes né(e) en France et l'un au moins de vos parents est né en France",
        },
        {
          value: "NE_EN_FR_ET_PARENT_NE_ANCIEN_DEP_TER_FR",
          text:
            "Vous êtes né(e) en France et l'un au moins de vos parents est né dans un ancien département ou territoire français",
        },
        {
          value: "NE_EN_FR_ET_PARENT_FR",
          text:
            "Vous êtes né(e) en France et l'un au moins de vos parents est français",
        },
        {
          value: "PAS_NE_EN_FR_ET_PARENT_FR",
          text:
            "Vous n'êtes pas né(e) en France et l'un au moins de vos parents est français",
        },
        {
          value: "PARENT_FR_AVANT_MAJ",
          text:
            "Votre mère ou votre père est devenu(s) français(e) avant votre majorité",
        },
        {
          value: "PAR_MARIAGE",
          text: "Vous êtes de nationalité française par mariage",
        },
        {
          value: "NE_EN_FR_ET_PARENT_PAS_FR",
          text: "Vous êtes né(e) en France et vos parents ne sont pas français",
        },
        { value: "NATUR_FR", text: "Vous êtes naturalisé(e) français(e)" },
        {
          value: "REINTEG_FR",
          text: "Vous avez été réintégré(e) dans la nationalité française",
        },
        {
          value: "PAR_DECLAR",
          text:
            "Vous êtes français(e) par déclaration (autrement que par mariage)",
        },
        { value: "AUTRE", text: "Autre motif" },
      ],
      prefixeLastnameValues: [
        { value: "Epouse", text: "Epouse" },
        { value: "Epoux", text: "Epoux" },
        { value: "Veuve", text: "Veuve" },
        { value: "Veuf", text: "Veuf" },
      ],
      areaPlace: [
        { value: null, text: "Choisissez..." },
        { value: "France", text: "FRANCE" },
        { value: "Autre", text: "A L'ÉTRANGER" },
      ],
      personTypes: [
        { value: "Adulte", text: "Adulte" },
        { value: "Mineur_Moins_15", text: "Mineur moins de 15 ans" },
        { value: "Mineur_Plus_15", text: "Mineur de 15 ans et plus" },
      ],
      yesNo: [
        { value: "Oui", text: "Oui" },
        { value: "Non", text: "Non" },
      ],
      documentTypes: [
        { value: "Passeport", text: "Passeport" },
        { value: "Carte_Identite", text: "Carte d'identité" },
      ],
      userTypes: [
        { value: "partner", text: "Professionel" },
        { value: "individual", text: "Particulier" },
      ],
      passeportReasons: [
        { value: null, text: "Choisissez..." },
        { value: "Premiere_demande", text: "Première demande" },
        { value: "Vol", text: "Renouvellement pour vol" },
        { value: "Perte", text: "Renouvellement pour perte" },
        {
          value: "Expiration",
          text: "Renouvellement pour cause d'expiration du passeport",
        },
        {
          value: "Rectification",
          text: "Renouvellement pour rectification du passeport",
        },
        {
          value: "Epuisement",
          text: "Renouvellement pour cause de pages épuisées sur le passeport",
        },
        {
          value: "Passeport_Delphine",
          text:
            "Passeport Delphine délivré à compter du 25 octobre 2005 et déplacement ou transit prévu pour les Etats-Unis",
        },
        { value: "Deterioration", text: "Renouvellement pour détérioration" },
      ],
      idCardReasons: [
        { value: null, text: "Choisissez..." },
        { value: "Premiere_demande", text: "Première demande" },
        { value: "Vol", text: "Renouvellement pour vol" },
        { value: "Perte", text: "Renouvellement pour perte" },
        {
          value: "Expiration",
          text: "Renouvellement pour cause d'expiration du passeport",
        },
        {
          value: "Rectification",
          text: "Renouvellement pour rectification du passeport",
        },
        { value: "Deterioration", text: "Renouvellement pour détérioration" },
      ],
      departements: [
        { value: null, text: "Choisissez..." },
        { value: "01", text: "AIN" },
        { value: "02", text: "AISNE" },
        { value: "03", text: "ALLIER" },
        { value: "04", text: "ALPES-DE-HAUTE-PROVENCE" },
        { value: "05", text: "HAUTES-ALPES" },
        { value: "06", text: "ALPES-MARITIMES" },
        { value: "07", text: "ARDECHE" },
        { value: "08", text: "ARDENNES" },
        { value: "09", text: "ARIEGE" },
        { value: "10", text: "AUBE" },
        { value: "11", text: "AUDE" },
        { value: "12", text: "AVEYRON" },
        { value: "13", text: "BOUCHES-DU-RHONE" },
        { value: "14", text: "CALVADOS" },
        { value: "15", text: "CANTAL" },
        { value: "16", text: "CHARENTE" },
        { value: "17", text: "CHARENTE-MARITIME" },
        { value: "18", text: "CHER" },
        { value: "19", text: "CORREZE" },
        { value: "20", text: "CORSE" },
        { value: "21", text: "COTE-D'OR" },
        { value: "22", text: "COTES-D'ARMOR" },
        { value: "23", text: "CREUSE" },
        { value: "24", text: "DORDOGNE" },
        { value: "25", text: "DOUBS" },
        { value: "26", text: "DROME" },
        { value: "27", text: "EURE" },
        { value: "28", text: "EURE-ET-LOIR" },
        { value: "29", text: "FINISTERE" },
        { value: "2A", text: "CORSE-DU-SUD" },
        { value: "2B", text: "HAUTE-CORSE" },
        { value: "30", text: "GARD" },
        { value: "31", text: "HAUTE-GARONNE" },
        { value: "32", text: "GERS" },
        { value: "33", text: "GIRONDE" },
        { value: "34", text: "HERAULT" },
        { value: "35", text: "ILLE-ET-VILAINE" },
        { value: "36", text: "INDRE" },
        { value: "37", text: "INDRE-ET-LOIRE" },
        { value: "38", text: "ISERE" },
        { value: "39", text: "JURA" },
        { value: "40", text: "LANDES" },
        { value: "41", text: "LOIR-ET-CHER" },
        { value: "42", text: "LOIRE" },
        { value: "43", text: "HAUTE-LOIRE" },
        { value: "44", text: "LOIRE-ATLANTIQUE" },
        { value: "45", text: "LOIRET" },
        { value: "46", text: "LOT" },
        { value: "47", text: "LOT-ET-GARONNE" },
        { value: "48", text: "LOZERE" },
        { value: "49", text: "MAINE-ET-LOIRE" },
        { value: "50", text: "MANCHE" },
        { value: "51", text: "MARNE" },
        { value: "52", text: "HAUTE-MARNE" },
        { value: "53", text: "MAYENNE" },
        { value: "54", text: "MEURTHE-ET-MOSELLE" },
        { value: "55", text: "MEUSE" },
        { value: "56", text: "MORBIHAN" },
        { value: "57", text: "MOSELLE" },
        { value: "58", text: "NIEVRE" },
        { value: "59", text: "NORD" },
        { value: "60", text: "OISE" },
        { value: "61", text: "ORNE" },
        { value: "62", text: "PAS-DE-CALAIS" },
        { value: "63", text: "PUY-DE-DOME" },
        { value: "64", text: "PYRENEES-ATLANTIQUES" },
        { value: "65", text: "HAUTES-PYRENEES" },
        { value: "66", text: "PYRENEES-ORIENTALES" },
        { value: "67", text: "BAS-RHIN" },
        { value: "68", text: "HAUT-RHIN" },
        { value: "69", text: "RHONE" },
        { value: "70", text: "HAUTE-SAONE" },
        { value: "71", text: "SAONE-ET-LOIRE" },
        { value: "72", text: "SARTHE" },
        { value: "73", text: "SAVOIE" },
        { value: "74", text: "HAUTE-SAVOIE" },
        { value: "75", text: "PARIS" },
        { value: "76", text: "SEINE-MARITIME" },
        { value: "77", text: "SEINE-ET-MARNE" },
        { value: "78", text: "YVELINES" },
        { value: "79", text: "DEUX-SEVRES" },
        { value: "80", text: "SOMME" },
        { value: "81", text: "TARN" },
        { value: "82", text: "TARN-ET-GARONNE" },
        { value: "83", text: "VAR" },
        { value: "84", text: "VAUCLUSE" },
        { value: "85", text: "VENDEE" },
        { value: "86", text: "VIENNE" },
        { value: "87", text: "HAUTE-VIENNE" },
        { value: "88", text: "VOSGES" },
        { value: "89", text: "YONNE" },
        { value: "90", text: "TERRITOIRE DE BELFORT" },
        { value: "91", text: "ESSONNE" },
        { value: "92", text: "HAUTS-DE-SEINE" },
        { value: "93", text: "SEINE-SAINT-DENIS" },
        { value: "94", text: "VAL-DE-MARNE" },
        { value: "95", text: "VAL-D'OISE" },
      ],
      sexes: [
        { value: "Femme", text: "Femme" },
        { value: "Homme", text: "Homme" },
      ],
      lastnameOrigines: [
        { value: "Pere", text: "Du père" },
        { value: "Mere", text: "De la mère" },
        { value: "Epouse", text: "Epouse" },
        { value: "Epoux", text: "Epoux" },
      ],
      eyesColors: [
        { value: null, text: "Choisissez..." },
        { value: "AUTRE", text: "AUTRE" },
        { value: "ALBINOS", text: "ALBINOS" },
        { value: "BLEUE", text: "BLEUE" },
        { value: "BLEU_GRIS", text: "BLEU-GRIS" },
        { value: "BLEU_VERT", text: "BLEU-VERT" },
        { value: "GRISE", text: "GRISE" },
        { value: "GRIS_VERT", text: "GRIS-VERT" },
        { value: "MARRON", text: "MARRON" },
        { value: "MARRON_VERT", text: "MARRON-VERT" },
        { value: "NOIRE", text: "NOIRE" },
        { value: "NOISETTE", text: "NOISETTE" },
        { value: "VAIRON", text: "VAIRON" },
        { value: "VERTE", text: "VERTE" },
      ],
      birthCountryPlaces: [
        { value: null, text: "Choisissez..." },
        { value: "1", text: "AFARS ET ISSAS" },
        { value: "2", text: "AFGHANISTAN" },
        { value: "3", text: "AFRIQUE DU SUD" },
        { value: "4", text: "ALBANIE" },
        { value: "5", text: "ALGÉRIE" },
        { value: "6", text: "ALLEMAGNE" },
        { value: "7", text: "ANDORRE" },
        { value: "8", text: "ANGOLA" },
        { value: "9", text: "ANGUILLA" },
        { value: "10", text: "ANTARCTIQUE" },
        { value: "11", text: "ANTARCTIQUE, TERRITOIRE BRITANNIQUE DE L'" },
        { value: "12", text: "ANTIGUA-ET-BARBUDA" },
        { value: "13", text: "ANTILLES NÉERLANDAISES" },
        { value: "14", text: "APATRIDE" },
        { value: "15", text: "ARABIE SAOUDITE" },
        { value: "16", text: "ARGENTINE" },
        { value: "17", text: "ARMÉNIE" },
        { value: "18", text: "ARUBA" },
        { value: "19", text: "AUSTRALIE" },
        { value: "20", text: "AUTRICHE" },
        { value: "21", text: "AZERBAIDJAN" },
        { value: "22", text: "BAHAMAS (LES)" },
        { value: "23", text: "BAHREIN" },
        { value: "24", text: "BANGLADESH" },
        { value: "25", text: "BARBADE (LA)" },
        { value: "26", text: "BELGIQUE" },
        { value: "27", text: "BELIZE" },
        { value: "29", text: "BERMUDES" },
        { value: "30", text: "BHOUTAN" },
        { value: "32", text: "BIRMANIE" },
        { value: "31", text: "BIÉLORUSSIE" },
        { value: "33", text: "BOLIVIE" },
        { value: "34", text: "BOSNIE-HERZÉGOVINE" },
        { value: "35", text: "BOTSWANA" },
        { value: "36", text: "BOUVET (ILES)" },
        { value: "38", text: "BRUNÉI" },
        { value: "37", text: "BRÉSIL" },
        { value: "39", text: "BULGARIE" },
        { value: "40", text: "BURKINA" },
        { value: "41", text: "BURUNDI" },
        { value: "28", text: "BÉNIN" },
        { value: "42", text: "CAIMANES (ILES)" },
        { value: "43", text: "CAMBODGE" },
        { value: "44", text: "CAMEROUN" },
        { value: "45", text: "CANADA" },
        { value: "46", text: "CANTON ET ENDERBURY (ILES)" },
        { value: "47", text: "CAP-VERT" },
        { value: "48", text: "CENTRAFRIQUE" },
        { value: "49", text: "CEYLAN" },
        { value: "50", text: "CHILI" },
        { value: "51", text: "CHINE" },
        { value: "52", text: "CHRISTMAS (ILES)" },
        { value: "53", text: "CHYPRE" },
        { value: "54", text: "COCOS (ILES) (KEELING)" },
        { value: "55", text: "COLOMBIE" },
        { value: "56", text: "COMORES" },
        { value: "57", text: "CONGO" },
        { value: "59", text: "COREE DU SUD" },
        { value: "58", text: "CORÉE DU NORD" },
        { value: "60", text: "COSTA RICA" },
        { value: "61", text: "COTE D'IVOIRE" },
        { value: "62", text: "CROATIE" },
        { value: "63", text: "CUBA" },
        { value: "64", text: "DAHOMEY" },
        { value: "65", text: "DANEMARK" },
        { value: "66", text: "DJIBOUTI" },
        { value: "67", text: "DOMINIQUE" },
        { value: "69", text: "EL SALVADOR" },
        { value: "73", text: "ESPAGNE" },
        { value: "74", text: "ESTONIE" },
        { value: "77", text: "FALKLAND (ILES) (MALVINAS)" },
        { value: "79", text: "FIDJI" },
        { value: "80", text: "FINLANDE" },
        { value: "81", text: "FRANCE" },
        { value: "78", text: "FÉROÉ (ILES)" },
        { value: "82", text: "GABON" },
        { value: "83", text: "GAMBIE" },
        { value: "86", text: "GHANA" },
        { value: "87", text: "GIBRALTAR" },
        { value: "88", text: "GILBERT ET ELLICE, ILES" },
        { value: "89", text: "GRECE" },
        { value: "90", text: "GRENADE" },
        { value: "91", text: "GROENLAND" },
        { value: "92", text: "GUAM" },
        { value: "93", text: "GUATEMALA" },
        { value: "94", text: "GUINÉE" },
        { value: "95", text: "GUINÉE ÉQUATORIALE" },
        { value: "96", text: "GUINÉE-BISSAO" },
        { value: "97", text: "GUYANA" },
        { value: "84", text: "GÉORGIE" },
        { value: "85", text: "GÉORGIE DU SUD ET LES ILES SANDWICH DU SUD" },
        { value: "98", text: "HAITI" },
        { value: "99", text: "HAUTE-VOLTA" },
        { value: "100", text: "HEARD, ILES ET MCDONALD, ILES" },
        { value: "101", text: "HONDURAS" },
        { value: "102", text: "HONG KONG" },
        { value: "103", text: "HONGRIE" },
        { value: "104", text: "ILES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS" },
        { value: "105", text: "ILES VIERGES BRITANNIQUES" },
        { value: "106", text: "ILES VIERGES DES ÉTATS-UNIS" },
        { value: "107", text: "INDE" },
        { value: "109", text: "INDONÉSIE" },
        { value: "108", text: "INDÉFINIE" },
        { value: "110", text: "IRAK" },
        { value: "111", text: "IRAN" },
        { value: "112", text: "IRLANDE" },
        { value: "113", text: "ISLANDE" },
        { value: "114", text: "ISRAEL" },
        { value: "115", text: "ITALIE" },
        { value: "116", text: "JAMAIQUE" },
        { value: "117", text: "JAPON" },
        { value: "118", text: "JERUSALEM" },
        { value: "119", text: "JOHNSTON, ILE" },
        { value: "120", text: "JORDANIE" },
        { value: "121", text: "KAZAKHSTAN" },
        { value: "122", text: "KENYA" },
        { value: "123", text: "KIRIBATI" },
        { value: "124", text: "KIRZGHIZISTAN" },
        { value: "125", text: "KOSOVO" },
        { value: "126", text: "KOWEIT" },
        { value: "127", text: "LAOS" },
        { value: "128", text: "LES COOK" },
        { value: "129", text: "LES MARSHALL" },
        { value: "130", text: "LESOTHO" },
        { value: "131", text: "LETTONIE" },
        { value: "132", text: "LIBAN" },
        { value: "134", text: "LIBYE" },
        { value: "133", text: "LIBÉRIA" },
        { value: "135", text: "LIECHTENSTEIN" },
        { value: "136", text: "LITUANIE" },
        { value: "137", text: "LUXEMBOURG" },
        { value: "138", text: "MACAO" },
        { value: "139", text: "MACÉDOINE" },
        { value: "140", text: "MADAGASCAR" },
        { value: "141", text: "MALAISIE" },
        { value: "142", text: "MALAWI" },
        { value: "143", text: "MALDIVES" },
        { value: "144", text: "MALI" },
        { value: "145", text: "MALTE" },
        { value: "146", text: "MARIANNES DU NORD, ILES" },
        { value: "147", text: "MAROC" },
        { value: "148", text: "MAURICE" },
        { value: "149", text: "MAURITANIE" },
        { value: "150", text: "MEXIQUE" },
        { value: "151", text: "MICRONÉSIE" },
        { value: "152", text: "MIDWAY, ILES" },
        { value: "153", text: "MOLDAVIE" },
        { value: "154", text: "MONACO" },
        { value: "155", text: "MONGOLIE" },
        { value: "156", text: "MONTENEGRO" },
        { value: "157", text: "MONTSERRAT" },
        { value: "158", text: "MOZAMBIQUE" },
        { value: "159", text: "MYANMAR" },
        { value: "160", text: "NAMIBIE" },
        { value: "161", text: "NAURU" },
        { value: "163", text: "NICARAGUA" },
        { value: "164", text: "NIGER" },
        { value: "165", text: "NIGÉRIA" },
        { value: "166", text: "NIOUÉ" },
        { value: "167", text: "NORFOLK, ILE" },
        { value: "168", text: "NORVEGE" },
        { value: "169", text: "NOUVELLE-ZÉLANDE" },
        { value: "170", text: "NOUVELLES-HÉBRIDES" },
        { value: "162", text: "NÉPAL" },
        { value: "171", text: "OCÉAN INDIEN, TERRITOIRE BRITANNIQUE DE L'" },
        { value: "172", text: "OMAN" },
        { value: "173", text: "OUGANDA" },
        { value: "174", text: "OUZBÉKISTAN" },
        { value: "175", text: "PACIFIQUE, DIVERSES ILES DU (ÉTATS-UNIS)" },
        { value: "176", text: "PACIFIQUE, ILES DU (TERRITOIRE SOUS TUTELLE)" },
        { value: "177", text: "PAKISTAN" },
        { value: "178", text: "PALAOS" },
        { value: "179", text: "PALESTINIEN OCCUPÉ, TERRITOIRE" },
        { value: "180", text: "PANAMA" },
        { value: "181", text: "PANAMA, ZONE DU CANAL DE" },
        { value: "182", text: "PAPOUASIE-NOUVELLE-GUINÉE" },
        { value: "183", text: "PARAGUAY" },
        { value: "184", text: "PAYS-BAS" },
        { value: "186", text: "PHILIPPINES" },
        { value: "187", text: "PITCAIRN" },
        { value: "188", text: "POLOGNE" },
        { value: "189", text: "PORTO RICO" },
        { value: "190", text: "PORTUGAL" },
        { value: "185", text: "PÉROU" },
        { value: "191", text: "QATAR" },
        { value: "197", text: "RHODÉSIE DU SUD" },
        { value: "198", text: "ROUMANIE" },
        { value: "199", text: "ROYAUME-UNI" },
        { value: "200", text: "RUSSIE" },
        { value: "201", text: "RWANDA" },
        { value: "192", text: "RÉFUGIÉ (AUTRE STATUT)" },
        { value: "193", text: "RÉFUGIÉ CONVENTION DE 1951" },
        { value: "194", text: "RÉP. DÉMOCRATIQUE DU CONGO" },
        { value: "195", text: "RÉPUBLIQUE DOMINICAINE" },
        { value: "196", text: "RÉPUBLIQUE TCHÈQUE" },
        { value: "202", text: "SAHARA OCCIDENTAL" },
        { value: "203", text: "SAINT-KITTS-ET-NEVIS" },
        { value: "204", text: "SAINT-MARIN" },
        { value: "205", text: "SAINT-SIEGE (VATICAN)" },
        { value: "206", text: "SAINT-VINCENT-ET-LES GRENADINES" },
        { value: "207", text: "SAINTE-HÉLÈNE" },
        { value: "208", text: "SAINTE-LUCIE" },
        { value: "209", text: "SALOMON" },
        { value: "210", text: "SAMOA" },
        { value: "211", text: "SAMOA AMERICAINES" },
        { value: "212", text: "SAO TOMÉ-ET-PRINCIPE" },
        { value: "214", text: "SERBIE" },
        { value: "215", text: "SERBIE-ET-MONTÉNÉGRO" },
        { value: "216", text: "SEYCHELLES" },
        { value: "217", text: "SIERRA LEONE" },
        { value: "218", text: "SIKKIM" },
        { value: "219", text: "SINGAPOUR" },
        { value: "220", text: "SLOVAQUIE" },
        { value: "221", text: "SLOVÉNIE" },
        { value: "222", text: "SOMALIE" },
        { value: "223", text: "SOUDAN" },
        { value: "224", text: "SOUDAN DU SUD" },
        { value: "225", text: "SRI LANKA" },
        { value: "226", text: "SUEDE" },
        { value: "227", text: "SUISSE" },
        { value: "228", text: "SURINAME" },
        { value: "229", text: "SVALBARD ET ILE JAN MAYEN" },
        { value: "230", text: "SWAZILAND" },
        { value: "231", text: "SYRIE" },
        { value: "213", text: "SÉNÉGAL" },
        { value: "232", text: "TADJIKISTAN" },
        { value: "233", text: "TAIWAN" },
        { value: "234", text: "TANZANIE" },
        { value: "235", text: "TCHAD" },
        { value: "236", text: "TCHÉCOSLOVAQUIE" },
        { value: "237", text: "TERRE DE LA REINE MAUD" },
        { value: "238", text: "THAILANDE" },
        { value: "239", text: "TIMOR" },
        { value: "240", text: "TOGO" },
        { value: "241", text: "TOKELAU" },
        { value: "242", text: "TONGA" },
        { value: "243", text: "TRINITÉ-ET-TOBAGO" },
        { value: "244", text: "TUNISIE" },
        { value: "245", text: "TURKMÉNISTAN" },
        { value: "246", text: "TURKS ET CAIQUES, ILES" },
        { value: "247", text: "TURQUIE" },
        { value: "248", text: "TUVALU" },
        { value: "249", text: "UKRAINE" },
        { value: "250", text: "URSS" },
        { value: "251", text: "URUGUAY" },
        { value: "252", text: "VANUATU" },
        { value: "253", text: "VENEZUELA" },
        { value: "254", text: "VIET-NAM, RÉPUBLIQUE DÉMOCRATIQUE DU" },
        { value: "255", text: "VIETNAM" },
        { value: "256", text: "WAKE, ILE DE" },
        { value: "258", text: "YOUGOSLAVIE" },
        { value: "257", text: "YÉMEN" },
        { value: "259", text: "ZAIRE" },
        { value: "260", text: "ZAMBIE" },
        { value: "261", text: "ZIMBABWE" },
        { value: "262", text: "ZONE NEUTRE" },
        { value: "68", text: "ÉGYPTE" },
        { value: "70", text: "ÉMIRATS ARABES UNIS" },
        { value: "71", text: "ÉQUATEUR" },
        { value: "72", text: "ÉRYTHRÉE" },
        { value: "75", text: "ÉTATS UNIS" },
        { value: "76", text: "ÉTHIOPIE" },
      ],
    };
  },
  methods: {
    validateEmail(email) {
      if (/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]{2,})*$/.test(email)){
        return true
      }
      return false
    },
    goodPassword(password) {
      return (
        password.length >= 8 &&
        /[a-z]/.test(password) &&
        /[A-Z]/.test(password) &&
        /[0-9]/.test(password)
      );
    },
    mapValueToText(values, value) {
      for (let i = 0; i < values.length; i++) {
        if (value === null) {
          return "";
        }
        if (values[i].value === value) {
          return values[i].text;
        }
      }
      return "";
    },
    mapValuesToText(values, choices) {
      let result = "";
      for (let i = 0; i < values.length; i++) {
        if (choices === null) {
          return "";
        }
        for (let j = 0; j < choices.length; j++) {
          if (choices[j] === values[i].value) {
            result += values[i].text + ". ";
          }
        }
      }
      return result;
    },
  },
})
