export const UserType = {
  individual: 'individual',
  partner: 'partner',
  client: 'client',
  admin: 'admin',
  all: ''
}

export default {
  RENOUVELLEMENT: 'RENOUVELLEMENT',
  DECLARATION_PERTE: 'DÉCLARATION DE PERTE',

  
  VERROUILLER_UN_DOCUMENT: 'VERROUILLER UN DOCUMENT', 
  DEVERROUILLER_UN_DOCUMENT : 'DÉVERROUILLER UN DOCUMENT',
  DEMASQUER_UN_DOCUMENT: 'DÉMASQUER UN DOCUMENT D\'IDENTITÉ',
  MASQUER_UN_DOCUMENT: 'MASQUER UN DOCUMENT D\'IDENTITÉ',
  DEMANDE_AUTORISATION_ACCEPTE: 'DEMANDE D\’AUTORISATION ACCEPTÉ',
  DEMANDE_AUTORISATION_REFUSE: 'DEMANDE D\’AUTORISATION REFUSÉ',
  DEMANDE_AUTORISATION_SANS_REPONSE: 'DEMANDE D\’AUTORISATION SANS RÉPONSE',  
  RECHERCHE_ID: 'RECHERCHE DOCUMENT',
  ANALYSE: 'ANALYSE',
  PORTAIL: 'PORTAIL',

    /*
  CREATION_DOSSIER: 'CREATION DE DOSSIER',
  SUPPRESSION_DOSSIER: 'SUPPRESSION DE DOSSIER',
  MODIFICATION_DOSSIER: 'MODIFICATION DE DOSSIER',  
  CREATION_AUTORISATION: 'CREATION AUTORISATION',
  VALIDATION_AUTORISATION: 'VALIDATION AUTORISATION',
  SUPPRESSION_AUTORISATION: 'SUPPRESSION AUTORISATION',
  DEMANDE_AUTORISATION: 'DEMANDE AUTORISATION',
  CREATION_COMPTE: 'CREATION DE COMPTE',
  MODIFICATION_COMPTE: 'MODIFICATION DE COMPTE',
  SUPPRESSION_COMPTE: 'SUPPRESSION DE COMPTE',
  SYSTEME: 'SYSTEME',
  ADMIN: 'ADMIN',
  INDIVIDUAL: 'individual',
  PARTNER: 'partner',*/

  
  PRICES: {
    DECLARATION_PERTE: 9.99,
    HIGH: 125.99,
    MEDIUM: 81.99,
    LOW: 56.99,
    MIN: 39.99,
    TIMBRE: 25,
    XMIN: 9.99,
    NULL: 0
  }
}
