export enum PRICE_RENEWAL {
    TOUS_CAS_CNI = 0,
    ANCIEN_DOCUMENT_PERDU = 25,
    MAJEUR_PP = 86,
    MINEUR_MOINS_15_ANS_PP = 17,
    MINEUR_PLUS_15_ANS_PP = 42,
    IDP_PRICE = 39.99,
    SAUVER_DOC_RENOUVELLEMENT = 9.99
}